# Generated by Django 5.0.7 on 2024-07-30 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_inicio_inscripcion', models.DateField()),
                ('fecha_fin_inscripcion', models.DateField()),
                ('genero', models.BooleanField()),
                ('numero_clasificados_por_grupo', models.IntegerField()),
                ('numero_equipos_por_grupo', models.IntegerField()),
                ('numero_grupo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_disciplina', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('nombre_representante', models.CharField(max_length=100)),
                ('color_uniforme', models.CharField(max_length=50)),
                ('genero', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Escenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('numero_camisa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('sexo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_derrota_sin_jugar', models.IntegerField()),
                ('puntos_por_empate', models.IntegerField()),
                ('puntos_por_perdida', models.IntegerField()),
                ('puntos_por_victoria', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TablaPosiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField()),
                ('partidos_jugados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_encuentro', models.DateField()),
                ('tipo_evento', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDeportes.campeonato')),
                ('equipo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo1', to='AppDeportes.equipo')),
                ('equipo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo2', to='AppDeportes.equipo')),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDeportes.escenario')),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.CharField(max_length=50)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDeportes.campeonato')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDeportes.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.CharField(max_length=50)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDeportes.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDeportes.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='NominaEncuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titularidad', models.BooleanField()),
                ('encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDeportes.encuentro')),
            ],
        ),
        migrations.CreateModel(
            name='Amonestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_tarjeta', models.CharField(max_length=50)),
                ('nomina_encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDeportes.nominaencuentro')),
            ],
        ),
        migrations.AddField(
            model_name='jugador',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppDeportes.persona'),
        ),
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anios_experiencia', models.IntegerField()),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppDeportes.persona')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramacionJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDeportes.jornada')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcador', models.CharField(max_length=50)),
                ('nombre_goleador', models.CharField(max_length=100)),
                ('encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDeportes.encuentro')),
            ],
        ),
    ]
